DROP TABLE categoria CASCADE;
DROP TABLE filmes CASCADE;
DROP TABLE midias CASCADE;
DROP TABLE cliente CASCADE;
DROP TABLE locacao CASCADE;
DROP TABLE atores CASCADE;
DROP TABLE participacao CASCADE;

CREATE TABLE categoria(
	id_categoria serial PRIMARY KEY,
	nome varchar (20)
);
CREATE TABLE filmes(
	id_filme serial PRIMARY KEY,
	titulo varchar(60),
	id_categoria integer NOT NULL REFERENCES categoria ON DELETE RESTRICT
);
CREATE TABLE midias(
	id_midia serial PRIMARY KEY,
	tipo varchar (20),
	numero_volumes int,
	id_filme integer NOT NULL REFERENCES filmes ON DELETE RESTRICT
);
CREATE TABLE cliente(
	id_cliente serial PRIMARY KEY,
	cpf varchar (11),
	endereco varchar (40),
	nome varchar (30)
);
CREATE TABLE locacao(
	id_cliente integer NOT NULL REFERENCES cliente ON DELETE RESTRICT,
	id_midia integer NOT NULL REFERENCES midias ON DELETE RESTRICT,
	valor float,
	data date,
	PRIMARY KEY (id_cliente, id_midia)
);
CREATE TABLE  atores(
	id_ator serial PRIMARY KEY,
	nome varchar (30),
	data_nasc DATE
);
CREATE TABLE participacao(
	id_filme integer NOT NULL REFERENCES filmes,
	id_ator integer NOT NULL REFERENCES atores,
	PRIMARY KEY(id_filme, id_ator)
);
insert into categoria values (default, 'Ação');
insert into categoria values (default, 'Animação');
insert into categoria values (default, 'Aventura');
insert into categoria values (default, 'Comédia');
insert into categoria values (default, 'Documentário');
insert into categoria values (default, 'Drama');
insert into categoria values (default, 'Família');
insert into categoria values (default, 'Fantasia');
insert into categoria values (default, 'Ficção científica');
insert into categoria values (default, 'Filme noir');
insert into categoria values (default, 'Guerra');
insert into categoria values (default, 'Musical');
insert into categoria values (default, 'Policial');
insert into categoria values (default, 'Romance');
insert into categoria values (default, 'Suspense');
insert into categoria values (default, 'Terror');
insert into categoria values (default, 'Thriller');
insert into categoria values (default, 'Western');

INSERT INTO filmes VALUES(default,'Os Sete Samurais',1);
INSERT INTO filmes VALUES(default,'Apocalypse Now',1);
INSERT INTO filmes VALUES(default,'O Tesouro de Sierra Madre',1);
INSERT INTO filmes VALUES(default,'Guerra nas Estrelas: Episódio 4 - Uma Nova Esperança',1);
INSERT INTO filmes VALUES(default,'Ran',1);
INSERT INTO filmes VALUES(default,'No Tempo das Diligências',1);
INSERT INTO filmes VALUES(default,'Sem Novidades no Front',1);
INSERT INTO filmes VALUES(default,'King Kong',1);
INSERT INTO filmes VALUES(default,'Os Caçadores da Arca Perdida',1);
INSERT INTO filmes VALUES(default,'As Aventuras de Robin Hood',1);
INSERT INTO filmes VALUES(default,'Trono Manchado de Sangue',1);
INSERT INTO filmes VALUES(default,'Guerra nas Estrelas: Episódio 5 - O Império Contra-Ataca',1);
INSERT INTO filmes VALUES(default,'Alexandre Nevski',1);
INSERT INTO filmes VALUES(default,'Operação França',1);
INSERT INTO filmes VALUES(default,'Cidade de Deus',1);
INSERT INTO filmes VALUES(default,'Platoon',1);
INSERT INTO filmes VALUES(default,'Rio Vermelho',1);
INSERT INTO filmes VALUES(default,'O Inimigo Público',1);
INSERT INTO filmes VALUES(default,'Yojimbo - O Guarda-Costas',1);
INSERT INTO filmes VALUES(default,'Era uma Vez no Oeste',1);
INSERT INTO filmes VALUES(default,'Aliens - O Resgate',1);
INSERT INTO filmes VALUES(default,'Ben-Hur',1);
INSERT INTO filmes VALUES(default,'Spartacus',1);
INSERT INTO filmes VALUES(default,'O Resgate do Soldado Ryan',1);
INSERT INTO filmes VALUES(default,'O Exterminador do Futuro 2 - O Julgamento Final',1);
INSERT INTO filmes VALUES(default,'O Senhor dos Anéis - O Retorno do Rei',1);
INSERT INTO filmes VALUES(default,'Guerra nas Estrelas: Episódio 6 - O Retorno de Jedi',1);
INSERT INTO filmes VALUES(default,'O Indomado',1);
INSERT INTO filmes VALUES(default,'Henrique V',1);
INSERT INTO filmes VALUES(default,'De Volta para o Futuro',1);
INSERT INTO filmes VALUES(default,'O Homem Mosca',1);
INSERT INTO filmes VALUES(default,'Duro de Matar',1);
INSERT INTO filmes VALUES(default,'Sem Destino',1);
INSERT INTO filmes VALUES(default,'Os Vampiros',1);
INSERT INTO filmes VALUES(default,'O Exterminador do Futuro',1);
INSERT INTO filmes VALUES(default,'O Senhor dos Anéis - A Sociedade do Anel',1);
INSERT INTO filmes VALUES(default,'Por um Punhado de Dólares',1);
INSERT INTO filmes VALUES(default,'O Mais Longo dos Dias',1);
INSERT INTO filmes VALUES(default,'Os Doze Condenados',1);
INSERT INTO filmes VALUES(default,'007 Contra Goldfinger',1);
INSERT INTO filmes VALUES(default,'O Samurai Dominante',1);
INSERT INTO filmes VALUES(default,'Perseguidor Implacável',1);
INSERT INTO filmes VALUES(default,'Somente Deus por Testemunha',1);
INSERT INTO filmes VALUES(default,'O Trem',1);
INSERT INTO filmes VALUES(default,'Fugindo do Inferno',1);
INSERT INTO filmes VALUES(default,'Corra Lola Corra',1);
INSERT INTO filmes VALUES(default,'Por uns Dólares a Mais',1);
INSERT INTO filmes VALUES(default,'O Ladrão de Bagdá',1);
INSERT INTO filmes VALUES(default,'Zulu',1);
INSERT INTO filmes VALUES(default,'Matrix',1);
INSERT INTO filmes VALUES(default,'Batman - O Cavaleiro das Trevas',1);
INSERT INTO filmes VALUES(default,'Jornada nas Estrelas 2 - A Ira de Kahn',1);
INSERT INTO filmes VALUES(default,'Moscou Contra 007',1);
INSERT INTO filmes VALUES(default,'Rocky, um Lutador',1);
INSERT INTO filmes VALUES(default,'Capitão Blood',1);
INSERT INTO filmes VALUES(default,'Auroras Nascem Tranqüilas',1);
INSERT INTO filmes VALUES(default,'Bullitt',1);
INSERT INTO filmes VALUES(default,'Kill Bill: Vol. 1',1);
INSERT INTO filmes VALUES(default,'Peking Opera Blues',1);
INSERT INTO filmes VALUES(default,'O Senhor dos Anéis - As Duas Torres',1);
INSERT INTO filmes VALUES(default,'Branca de Neve e os Sete Anões',2);
INSERT INTO filmes VALUES(default,'A Viagem de Chihiro',2);
INSERT INTO filmes VALUES(default,'Procurando Nemo',2);
INSERT INTO filmes VALUES(default,'Fantasia',2);
INSERT INTO filmes VALUES(default,'Pinóquio',2);
INSERT INTO filmes VALUES(default,'Princesa Mononoke',2);
INSERT INTO filmes VALUES(default,'Shrek',2);
INSERT INTO filmes VALUES(default,'Meu Vizinho Totoro',2);
INSERT INTO filmes VALUES(default,'O Túmulo dos Vagalumes',2);
INSERT INTO filmes VALUES(default,'Bambi',2);
INSERT INTO filmes VALUES(default,'O Castelo Animado',2);
INSERT INTO filmes VALUES(default,'A Bela e a Fera',2);
INSERT INTO filmes VALUES(default,'O Rei Leão',2);
INSERT INTO filmes VALUES(default,'Os Incríveis',2);
INSERT INTO filmes VALUES(default,'Laputa, o Castelo no Céu',2);
INSERT INTO filmes VALUES(default,'Monstros S.A.',2);
INSERT INTO filmes VALUES(default,'Toy Story',2);
INSERT INTO filmes VALUES(default,'Nausicaä do Vale dos Ventos',2);
INSERT INTO filmes VALUES(default,'Millennium Actress',2);
INSERT INTO filmes VALUES(default,'As Aventuras do Príncipe Achmed',2);
INSERT INTO filmes VALUES(default,'Whisper of the Heart',2);
INSERT INTO filmes VALUES(default,'Up – Altas Aventuras',2);
INSERT INTO filmes VALUES(default,'A Dama e o Vagabundo',2);
INSERT INTO filmes VALUES(default,'Wall-E',2);
INSERT INTO filmes VALUES(default,'O Fantasma do Futuro',2);
INSERT INTO filmes VALUES(default,'O Planeta Selvagem',2);
INSERT INTO filmes VALUES(default,'As Bicicletas de Belleville',2);
INSERT INTO filmes VALUES(default,'Barefoot Gen',2);
INSERT INTO filmes VALUES(default,'Kiki s Delivery Service',2);
INSERT INTO filmes VALUES(default,'Akira',2);
INSERT INTO filmes VALUES(default,'Kirikou e a Feiticeira',2);
INSERT INTO filmes VALUES(default,'Neon Genesis Evangelion: The End of Evangelion',2);
INSERT INTO filmes VALUES(default,'Persépolis',2);
INSERT INTO filmes VALUES(default,'Valsa com Bashir',2);
INSERT INTO filmes VALUES(default,'Dumbo',2);
INSERT INTO filmes VALUES(default,'Shrek 2',2);
INSERT INTO filmes VALUES(default,'Uma Cilada para Roger Rabbit',2);
INSERT INTO filmes VALUES(default,'Wallace e Gromit: A Batalha dos Vegetais',2);
INSERT INTO filmes VALUES(default,'Ninja Scroll',2);
INSERT INTO filmes VALUES(default,'Ponyo - Uma Amizade que Veio do Mar',2);
INSERT INTO filmes VALUES(default,'O Gigante de Ferro',2);
INSERT INTO filmes VALUES(default,'Alice',2);
INSERT INTO filmes VALUES(default,'When the Wind Blows',2);
INSERT INTO filmes VALUES(default,'Memories',2);
INSERT INTO filmes VALUES(default,'O Estranho Mundo de Jack',2);
INSERT INTO filmes VALUES(default,'Interstella 5555',2);
INSERT INTO filmes VALUES(default,'Metrópolis',2);
INSERT INTO filmes VALUES(default,'Yellow Submarine',2);
INSERT INTO filmes VALUES(default,'Tokyo Godfathers',2);
INSERT INTO filmes VALUES(default,'Pinchcliffe Grand Prix',2);
INSERT INTO filmes VALUES(default,'Fullmetal Alchemist',2);
INSERT INTO filmes VALUES(default,'Watership Down',2);
INSERT INTO filmes VALUES(default,'Galaxy Express 999',2);
INSERT INTO filmes VALUES(default,'O Fantástico Sr. Raposo',2);
INSERT INTO filmes VALUES(default,'Only Yesterday',2);
INSERT INTO filmes VALUES(default,'Waking Life',2);
INSERT INTO filmes VALUES(default,'Ratatouille',2);
INSERT INTO filmes VALUES(default,'Vampire Hunter D',2);
INSERT INTO filmes VALUES(default,'Toy Story 2',2);
INSERT INTO filmes VALUES(default,'Porco Rosso',2);



INSERT INTO atores VALUES(default,'Akira Kurosawa','01-01-1970');
INSERT INTO atores VALUES(default,'Andrew Stanton','02-01-1970');
INSERT INTO atores VALUES(default,'Andy Wachowski','03-01-1970');
INSERT INTO atores VALUES(default,'Ari Folman','04-01-1970');
INSERT INTO atores VALUES(default,'Ben Sharpsteen','05-01-1970');
INSERT INTO atores VALUES(default,'Brad Bird','06-01-1970');
INSERT INTO atores VALUES(default,'Christopher Nolan','07-01-1970');
INSERT INTO atores VALUES(default,'Clyde Geronimi','08-01-1970');
INSERT INTO atores VALUES(default,'Cy Endfield','09-01-1970');
INSERT INTO atores VALUES(default,'David Hand','10-01-1970');
INSERT INTO atores VALUES(default,'Dennis Hopper','11-01-1970');
INSERT INTO atores VALUES(default,'Don Siegel','12-01-1970');
INSERT INTO atores VALUES(default,'Fernando Meirelles','13-01-1970');
INSERT INTO atores VALUES(default,'Francis Ford Coppola','14-01-1970');
INSERT INTO atores VALUES(default,'Fred C. Newmeyer','15-01-1970');
INSERT INTO atores VALUES(default,'Gary Trousdale','16-01-1970');
INSERT INTO atores VALUES(default,'George Dunning','17-01-1970');
INSERT INTO atores VALUES(default,'George Lucas','18-01-1970');
INSERT INTO atores VALUES(default,'Guy Hamilton','19-01-1970');
INSERT INTO atores VALUES(default,'Hamilton Luske','20-01-1970');
INSERT INTO atores VALUES(default,'Hayao Miyazaki','21-01-1970');
INSERT INTO atores VALUES(default,'Henry Selick','22-01-1970');
INSERT INTO atores VALUES(default,'Hideaki Anno','23-01-1970');
INSERT INTO atores VALUES(default,'Hiroshi Inagaki','24-01-1970');
INSERT INTO atores VALUES(default,'Howard Hawks','25-01-1970');
INSERT INTO atores VALUES(default,'Irvin Kershner','26-01-1970');
INSERT INTO atores VALUES(default,'Isao Takahata','27-01-1970');
INSERT INTO atores VALUES(default,'Ivo Caprino','28-01-1970');
INSERT INTO atores VALUES(default,'James Cameron','29-01-1970');
INSERT INTO atores VALUES(default,'Jan Svankmajer','30-01-1970');
INSERT INTO atores VALUES(default,'Jimmy T. Murakami','31-01-1970');
INSERT INTO atores VALUES(default,'John Ford','01-02-1970');
INSERT INTO atores VALUES(default,'John Frankenheimer','02-02-1970');
INSERT INTO atores VALUES(default,'John G. Avildsen','03-02-1970');
INSERT INTO atores VALUES(default,'John Huston','04-02-1970');
INSERT INTO atores VALUES(default,'John Lasseter','05-02-1970');
INSERT INTO atores VALUES(default,'John McTiernan','06-02-1970');
INSERT INTO atores VALUES(default,'John Sturges','07-02-1970');
INSERT INTO atores VALUES(default,'Katsuhiro Ôtomo','08-02-1970');
INSERT INTO atores VALUES(default,'Ken Annakin','09-02-1970');
INSERT INTO atores VALUES(default,'Kenneth Branagh','10-02-1970');
INSERT INTO atores VALUES(default,'Kôji Morimoto','11-02-1970');
INSERT INTO atores VALUES(default,'Leiji Matsumoto','12-02-1970');
INSERT INTO atores VALUES(default,'Lewis Milestone','13-02-1970');
INSERT INTO atores VALUES(default,'Lotte Reiniger','14-02-1970');
INSERT INTO atores VALUES(default,'Louis Feuillade','15-02-1970');
INSERT INTO atores VALUES(default,'Mamoru Oshî','16-02-1970');
INSERT INTO atores VALUES(default,'Martin Ritt','17-02-1970');
INSERT INTO atores VALUES(default,'Martin Rosen','18-02-1970');
INSERT INTO atores VALUES(default,'Merian C. Cooper','19-02-1970');
INSERT INTO atores VALUES(default,'Michael Curtiz','20-02-1970');
INSERT INTO atores VALUES(default,'Michel Ocelot','21-02-1970');
INSERT INTO atores VALUES(default,'Mori Masaki','22-02-1970');
INSERT INTO atores VALUES(default,'Nicholas Meyer','23-02-1970');
INSERT INTO atores VALUES(default,'Nick Park','24-02-1970');
INSERT INTO atores VALUES(default,'Oliver Stone','25-02-1970');
INSERT INTO atores VALUES(default,'Peter Docter','26-02-1970');
INSERT INTO atores VALUES(default,'Peter Jackson','27-02-1970');
INSERT INTO atores VALUES(default,'Peter Yates','28-02-1970');
INSERT INTO atores VALUES(default,'Quentin Tarantino','01-03-1970');
INSERT INTO atores VALUES(default,'Raoul Walsh','02-03-1970');
INSERT INTO atores VALUES(default,'René Laloux','03-03-1970');
INSERT INTO atores VALUES(default,'Richard Linklater','04-03-1970');
INSERT INTO atores VALUES(default,'Richard Marquand','05-03-1970');
INSERT INTO atores VALUES(default,'Rintaro','06-03-1970');
INSERT INTO atores VALUES(default,'Rob Minkoff','07-03-1970');
INSERT INTO atores VALUES(default,'Robert Aldrich','08-03-1970');
INSERT INTO atores VALUES(default,'Robert Zemeckis','09-03-1970');
INSERT INTO atores VALUES(default,'Roy Ward Baker','10-03-1970');
INSERT INTO atores VALUES(default,'Satoshi Kon','11-03-1970');
INSERT INTO atores VALUES(default,'Seiji Mizushima','12-03-1970');
INSERT INTO atores VALUES(default,'Sergei Eisenstein','13-03-1970');
INSERT INTO atores VALUES(default,'Sergio Leone','14-03-1970');
INSERT INTO atores VALUES(default,'Stanislav Rostotsky','15-03-1970');
INSERT INTO atores VALUES(default,'Stanley Kubrick','16-03-1970');
INSERT INTO atores VALUES(default,'Steven Spielberg','17-03-1970');
INSERT INTO atores VALUES(default,'Sylvain Chomet','18-03-1970');
INSERT INTO atores VALUES(default,'Terence Young','19-03-1970');
INSERT INTO atores VALUES(default,'Tom Tykwer','20-03-1970');
INSERT INTO atores VALUES(default,'Tsui Hark','21-03-1970');
INSERT INTO atores VALUES(default,'Vincent Paronnaud','22-03-1970');
INSERT INTO atores VALUES(default,'Walt Disney','23-03-1970');
INSERT INTO atores VALUES(default,'Wes Anderson','24-03-1970');
INSERT INTO atores VALUES(default,'William A. Wellman','25-03-1970');
INSERT INTO atores VALUES(default,'William Friedkin','26-03-1970');
INSERT INTO atores VALUES(default,'William Wyler','27-03-1970');
INSERT INTO atores VALUES(default,'Yoshiaki Kawajiri','28-03-1970');
INSERT INTO atores VALUES(default,'Yoshifumi Kondo','29-03-1970');
INSERT INTO atores VALUES(default,'Andrew Adamson','21-01-1976');
INSERT INTO atores VALUES(default,'James Algar','01-01-1965');


INSERT INTO midias VALUES(default, 'DVD',2,1);
INSERT INTO midias VALUES(default, 'DVD',3,2);
INSERT INTO midias VALUES(default, 'DVD',4,3);
INSERT INTO midias VALUES(default, 'DVD',5,4);
INSERT INTO midias VALUES(default, 'DVD',2,5);
INSERT INTO midias VALUES(default, 'DVD',1,6);
INSERT INTO midias VALUES(default, 'DVD',3,7);
INSERT INTO midias VALUES(default, 'DVD',4,8);
INSERT INTO midias VALUES(default, 'DVD',5,9);
INSERT INTO midias VALUES(default, 'DVD',6,10);
INSERT INTO midias VALUES(default, 'DVD',3,11);
INSERT INTO midias VALUES(default, 'DVD',2,12);
INSERT INTO midias VALUES(default, 'DVD',4,13);
INSERT INTO midias VALUES(default, 'DVD',5,14);
INSERT INTO midias VALUES(default, 'DVD',6,15);
INSERT INTO midias VALUES(default, 'DVD',7,16);
INSERT INTO midias VALUES(default, 'DVD',4,17);
INSERT INTO midias VALUES(default, 'DVD',3,18);
INSERT INTO midias VALUES(default, 'DVD',5,19);
INSERT INTO midias VALUES(default, 'DVD',6,20);
INSERT INTO midias VALUES(default, 'DVD',7,21);
INSERT INTO midias VALUES(default, 'DVD',8,22);
INSERT INTO midias VALUES(default, 'DVD',5,23);
INSERT INTO midias VALUES(default, 'DVD',4,24);
INSERT INTO midias VALUES(default, 'DVD',6,25);
INSERT INTO midias VALUES(default, 'DVD',8,26);
INSERT INTO midias VALUES(default, 'DVD',8,27);
INSERT INTO midias VALUES(default, 'DVD',9,28);
INSERT INTO midias VALUES(default, 'DVD',6,29);
INSERT INTO midias VALUES(default, 'DVD',5,30);
INSERT INTO midias VALUES(default, 'DVD',7,31);
INSERT INTO midias VALUES(default, 'DVD',8,32);
INSERT INTO midias VALUES(default, 'DVD',9,33);
INSERT INTO midias VALUES(default, 'DVD',10,34);
INSERT INTO midias VALUES(default, 'DVD',7,35);
INSERT INTO midias VALUES(default, 'DVD',6,36);
INSERT INTO midias VALUES(default, 'DVD',8,37);
INSERT INTO midias VALUES(default, 'DVD',9,38);
INSERT INTO midias VALUES(default, 'DVD',10,39);
INSERT INTO midias VALUES(default, 'DVD',11,40);
INSERT INTO midias VALUES(default, 'DVD',8,41);
INSERT INTO midias VALUES(default, 'DVD',7,42);
INSERT INTO midias VALUES(default, 'DVD',9,43);
INSERT INTO midias VALUES(default, 'DVD',10,44);
INSERT INTO midias VALUES(default, 'DVD',11,45);
INSERT INTO midias VALUES(default, 'DVD',12,46);
INSERT INTO midias VALUES(default, 'DVD',9,47);
INSERT INTO midias VALUES(default, 'DVD',8,48);
INSERT INTO midias VALUES(default, 'DVD',10,49);
INSERT INTO midias VALUES(default, 'DVD',11,50);
INSERT INTO midias VALUES(default, 'DVD',12,51);
INSERT INTO midias VALUES(default, 'DVD',13,52);
INSERT INTO midias VALUES(default, 'DVD',10,53);
INSERT INTO midias VALUES(default, 'DVD',9,54);
INSERT INTO midias VALUES(default, 'DVD',11,55);
INSERT INTO midias VALUES(default, 'DVD',12,56);
INSERT INTO midias VALUES(default, 'DVD',13,57);
INSERT INTO midias VALUES(default, 'DVD',14,58);
INSERT INTO midias VALUES(default, 'DVD',11,59);
INSERT INTO midias VALUES(default, 'DVD',10,60);
INSERT INTO midias VALUES(default, 'DVD',12,61);
INSERT INTO midias VALUES(default, 'DVD',13,62);
INSERT INTO midias VALUES(default, 'DVD',14,63);
INSERT INTO midias VALUES(default, 'DVD',15,64);
INSERT INTO midias VALUES(default, 'DVD',12,65);
INSERT INTO midias VALUES(default, 'DVD',11,66);
INSERT INTO midias VALUES(default, 'DVD',13,67);
INSERT INTO midias VALUES(default, 'DVD',14,68);
INSERT INTO midias VALUES(default, 'DVD',15,69);
INSERT INTO midias VALUES(default, 'DVD',16,70);
INSERT INTO midias VALUES(default, 'DVD',13,71);
INSERT INTO midias VALUES(default, 'DVD',12,72);
INSERT INTO midias VALUES(default, 'DVD',1,73);
INSERT INTO midias VALUES(default, 'DVD',13,74);
INSERT INTO midias VALUES(default, 'DVD',16,75);
INSERT INTO midias VALUES(default, 'DVD',17,76);
INSERT INTO midias VALUES(default, 'DVD',14,77);
INSERT INTO midias VALUES(default, 'DVD',13,78);
INSERT INTO midias VALUES(default, 'DVD',15,79);
INSERT INTO midias VALUES(default, 'DVD',16,80);
INSERT INTO midias VALUES(default, 'DVD',17,81);
INSERT INTO midias VALUES(default, 'DVD',18,82);
INSERT INTO midias VALUES(default, 'DVD',15,83);
INSERT INTO midias VALUES(default, 'DVD',14,84);
INSERT INTO midias VALUES(default, 'DVD',16,85);
INSERT INTO midias VALUES(default, 'DVD',17,86);
INSERT INTO midias VALUES(default, 'DVD',18,87);
INSERT INTO midias VALUES(default, 'DVD',19,88);
INSERT INTO midias VALUES(default, 'DVD',16,89);
INSERT INTO midias VALUES(default, 'DVD',15,90);
INSERT INTO midias VALUES(default, 'DVD',17,91);
INSERT INTO midias VALUES(default, 'DVD',18,92);
INSERT INTO midias VALUES(default, 'DVD',19,93);
INSERT INTO midias VALUES(default, 'DVD',20,94);
INSERT INTO midias VALUES(default, 'DVD',17,95);
INSERT INTO midias VALUES(default, 'DVD',16,96);
INSERT INTO midias VALUES(default, 'DVD',18,97);
INSERT INTO midias VALUES(default, 'DVD',19,98);
INSERT INTO midias VALUES(default, 'DVD',20,99);
INSERT INTO midias VALUES(default, 'DVD',21,100);
INSERT INTO midias VALUES(default, 'DVD',18,101);
INSERT INTO midias VALUES(default, 'DVD',17,102);
INSERT INTO midias VALUES(default, 'DVD',19,103);
INSERT INTO midias VALUES(default, 'DVD',20,104);
INSERT INTO midias VALUES(default, 'DVD',21,105);
INSERT INTO midias VALUES(default, 'DVD',22,106);
INSERT INTO midias VALUES(default, 'DVD',19,107);
INSERT INTO midias VALUES(default, 'DVD',18,108);
INSERT INTO midias VALUES(default, 'DVD',20,109);
INSERT INTO midias VALUES(default, 'DVD',21,110);
INSERT INTO midias VALUES(default, 'DVD',22,111);
INSERT INTO midias VALUES(default, 'DVD',23,112);
INSERT INTO midias VALUES(default, 'DVD',20,113);
INSERT INTO midias VALUES(default, 'DVD',19,114);
INSERT INTO midias VALUES(default, 'DVD',21,115);
INSERT INTO midias VALUES(default, 'DVD',22,116);
INSERT INTO midias VALUES(default, 'DVD',23,117);
INSERT INTO midias VALUES(default, 'DVD',24,118);
INSERT INTO midias VALUES(default, 'DVD',21,119);
INSERT INTO midias VALUES(default, 'DVD',20,120);
INSERT INTO midias VALUES(default, 'Blu-Ray',2,1);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,2);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,3);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,4);
INSERT INTO midias VALUES(default, 'Blu-Ray',2,5);
INSERT INTO midias VALUES(default, 'Blu-Ray',1,6);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,7);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,8);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,9);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,10);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,11);
INSERT INTO midias VALUES(default, 'Blu-Ray',2,12);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,13);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,14);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,15);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,16);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,17);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,18);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,19);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,20);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,21);
INSERT INTO midias VALUES(default, 'Blu-Ray',8,22);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,23);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,24);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,25);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,26);
INSERT INTO midias VALUES(default, 'Blu-Ray',8,27);
INSERT INTO midias VALUES(default, 'Blu-Ray',9,28);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,29);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,30);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,31);
INSERT INTO midias VALUES(default, 'Blu-Ray',8,32);
INSERT INTO midias VALUES(default, 'Blu-Ray',9,33);
INSERT INTO midias VALUES(default, 'Blu-Ray',10,34);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,35);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,36);
INSERT INTO midias VALUES(default, 'Blu-Ray',2,37);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,38);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,39);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,40);
INSERT INTO midias VALUES(default, 'Blu-Ray',2,41);
INSERT INTO midias VALUES(default, 'Blu-Ray',1,42);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,43);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,44);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,45);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,46);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,47);
INSERT INTO midias VALUES(default, 'Blu-Ray',2,48);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,49);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,50);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,51);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,52);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,53);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,54);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,55);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,56);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,57);
INSERT INTO midias VALUES(default, 'Blu-Ray',8,58);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,59);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,60);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,61);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,62);
INSERT INTO midias VALUES(default, 'Blu-Ray',8,63);
INSERT INTO midias VALUES(default, 'Blu-Ray',9,64);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,65);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,66);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,67);
INSERT INTO midias VALUES(default, 'Blu-Ray',8,68);
INSERT INTO midias VALUES(default, 'Blu-Ray',9,69);
INSERT INTO midias VALUES(default, 'Blu-Ray',15,70);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,71);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,72);
INSERT INTO midias VALUES(default, 'Blu-Ray',2,73);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,74);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,75);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,76);
INSERT INTO midias VALUES(default, 'Blu-Ray',2,77);
INSERT INTO midias VALUES(default, 'Blu-Ray',1,78);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,79);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,80);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,81);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,82);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,83);
INSERT INTO midias VALUES(default, 'Blu-Ray',2,84);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,85);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,86);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,87);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,88);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,89);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,90);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,91);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,92);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,93);
INSERT INTO midias VALUES(default, 'Blu-Ray',8,94);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,95);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,96);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,97);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,98);
INSERT INTO midias VALUES(default, 'Blu-Ray',8,99);
INSERT INTO midias VALUES(default, 'Blu-Ray',9,100);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,101);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,102);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,103);
INSERT INTO midias VALUES(default, 'Blu-Ray',8,104);
INSERT INTO midias VALUES(default, 'Blu-Ray',9,105);
INSERT INTO midias VALUES(default, 'Blu-Ray',10,106);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,107);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,108);
INSERT INTO midias VALUES(default, 'Blu-Ray',1,109);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,110);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,111);
INSERT INTO midias VALUES(default, 'Blu-Ray',2,112);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,113);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,114);
INSERT INTO midias VALUES(default, 'Blu-Ray',3,115);
INSERT INTO midias VALUES(default, 'Blu-Ray',5,116);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,117);
INSERT INTO midias VALUES(default, 'Blu-Ray',4,118);
INSERT INTO midias VALUES(default, 'Blu-Ray',6,119);
INSERT INTO midias VALUES(default, 'Blu-Ray',7,120);



ISERT INTO participacao VALUES (1,1);
ISERT INTO participacao VALUES (5,1);
ISERT INTO participacao VALUES (11,1);
ISERT INTO participacao VALUES (19,1);
ISERT INTO participacao VALUES (67,89);
ISERT INTO participacao VALUES (96,89);
ISERT INTO participacao VALUES (63,2);
ISERT INTO participacao VALUES (84,2);
ISERT INTO participacao VALUES (50,3);
ISERT INTO participacao VALUES (94,4);
ISERT INTO participacao VALUES (95,5);
ISERT INTO participacao VALUES (74,6);
ISERT INTO participacao VALUES (101,6);
ISERT INTO participacao VALUES (117,6);
ISERT INTO participacao VALUES (51,7);
ISERT INTO participacao VALUES (83,8);
ISERT INTO participacao VALUES (49,9);
ISERT INTO participacao VALUES (70,10);
ISERT INTO participacao VALUES (33,11);
ISERT INTO participacao VALUES (42,12);
ISERT INTO participacao VALUES (15,13);
ISERT INTO participacao VALUES (2,14);
ISERT INTO participacao VALUES (31,15);
ISERT INTO participacao VALUES (72,16);
ISERT INTO participacao VALUES (108,17);
ISERT INTO participacao VALUES (4,18);
ISERT INTO participacao VALUES (40,19);
ISERT INTO participacao VALUES (65,20);
ISERT INTO participacao VALUES (62,21);
ISERT INTO participacao VALUES (66,21);
ISERT INTO participacao VALUES (68,21);
ISERT INTO participacao VALUES (71,21);
ISERT INTO participacao VALUES (75,21);
ISERT INTO participacao VALUES (78,21);
ISERT INTO participacao VALUES (89,21);
ISERT INTO participacao VALUES (100,21);
ISERT INTO participacao VALUES (120,21);
ISERT INTO participacao VALUES (105,22);
ISERT INTO participacao VALUES (92,23);
ISERT INTO participacao VALUES (41,24);
ISERT INTO participacao VALUES (17,25);
ISERT INTO participacao VALUES (12,26);
ISERT INTO participacao VALUES (69,27);
ISERT INTO participacao VALUES (115,27);
ISERT INTO participacao VALUES (110,28);
ISERT INTO participacao VALUES (64,90);
ISERT INTO participacao VALUES (21,29);
ISERT INTO participacao VALUES (25,29);
ISERT INTO participacao VALUES (35,29);
ISERT INTO participacao VALUES (102,30);
ISERT INTO participacao VALUES (103,31);
ISERT INTO participacao VALUES (6,32);
ISERT INTO participacao VALUES (44,33);
ISERT INTO participacao VALUES (54,34);
ISERT INTO participacao VALUES (3,35);
ISERT INTO participacao VALUES (77,36);
ISERT INTO participacao VALUES (119,36);
ISERT INTO participacao VALUES (32,37);
ISERT INTO participacao VALUES (45,38);
ISERT INTO participacao VALUES (90,39);
ISERT INTO participacao VALUES (38,40);
ISERT INTO participacao VALUES (29,41);
ISERT INTO participacao VALUES (104,42);
ISERT INTO participacao VALUES (106,43);
ISERT INTO participacao VALUES (7,44);
ISERT INTO participacao VALUES (80,45);
ISERT INTO participacao VALUES (34,46);
ISERT INTO participacao VALUES (85,47);
ISERT INTO participacao VALUES (28,48);
ISERT INTO participacao VALUES (112,49);
ISERT INTO participacao VALUES (8,50);
ISERT INTO participacao VALUES (10,51);
ISERT INTO participacao VALUES (55,51);
ISERT INTO participacao VALUES (91,52);
ISERT INTO participacao VALUES (88,53);
ISERT INTO participacao VALUES (52,54);
ISERT INTO participacao VALUES (98,55);
ISERT INTO participacao VALUES (16,56);
ISERT INTO participacao VALUES (76,57);
ISERT INTO participacao VALUES (82,57);
ISERT INTO participacao VALUES (26,58);
ISERT INTO participacao VALUES (36,58);
ISERT INTO participacao VALUES (60,58);
ISERT INTO participacao VALUES (57,59);
ISERT INTO participacao VALUES (58,60);
ISERT INTO participacao VALUES (48,61);
ISERT INTO participacao VALUES (86,62);
ISERT INTO participacao VALUES (116,63);
ISERT INTO participacao VALUES (27,64);
ISERT INTO participacao VALUES (107,65);
ISERT INTO participacao VALUES (113,65);
ISERT INTO participacao VALUES (73,66);
ISERT INTO participacao VALUES (39,67);
ISERT INTO participacao VALUES (30,68);
ISERT INTO participacao VALUES (97,68);
ISERT INTO participacao VALUES (43,69);
ISERT INTO participacao VALUES (79,70);
ISERT INTO participacao VALUES (109,70);
ISERT INTO participacao VALUES (111,71);
ISERT INTO participacao VALUES (13,72);
ISERT INTO participacao VALUES (20,73);
ISERT INTO participacao VALUES (37,73);
ISERT INTO participacao VALUES (47,73);
ISERT INTO participacao VALUES (56,74);
ISERT INTO participacao VALUES (23,75);
ISERT INTO participacao VALUES (9,76);
ISERT INTO participacao VALUES (24,76);
ISERT INTO participacao VALUES (87,77);
ISERT INTO participacao VALUES (53,78);
ISERT INTO participacao VALUES (46,79);
ISERT INTO participacao VALUES (59,80);
ISERT INTO participacao VALUES (93,81);
ISERT INTO participacao VALUES (61,82);
ISERT INTO participacao VALUES (114,83);
ISERT INTO participacao VALUES (18,84);
ISERT INTO participacao VALUES (14,85);
ISERT INTO participacao VALUES (22,86);
ISERT INTO participacao VALUES (99,87);
ISERT INTO participacao VALUES (118,87);
ISERT INTO participacao VALUES (81,88);

